### ISSUE TITLE
Doesnt work whatsoever

### ISSUE THREAD

**Issue by 40P3** [BrenoLudgero/Auction_House_Notifications#1]
Not showing up on addons, not doing anything for /ahn command, not found, if this should work it doesnt for me. Latest version downloaded from wowinterface 1.2.0

**Comment by BrenoLudgero** [comment]
Hello @40P3!

I answered your comment in [WoWInterface](https://www.wowinterface.com/downloads/info26587-AuctionHouseNotifications.html#comments). Please let me know if we can work together to make the addon compatible with Retail.

**Comment by 40P3** [comment]
Hi @BrenoLudgero: My answer:

OHh okey thank you, I would love to get a retail version of this, looks cool and definitely a feature I'm missing from my trading experience. 

Yes I would def. test it for you.  :)

Might be some additional library is missing, but youre the coder I'm just guessing.

**Comment by 40P3** [comment]
Hi,

Thanks for the test zip. Happy to test it out.

Downloaded, unzipped.
Addon shows up properly now in addon list.
Entering in game, addon shows command line welcome message and loading succesfully.
Addon visible in addon list under options/addon window.
Settings can be modified, tested

Tried /ahn command line that didn't register when pushing enter button, chat text stays open, no errors in chat, however error on bugsack:

One error:
13x ...rfaceAuctionHouseNotifications/Interface.lua:9: attempt to call global 'InterfaceOptionsFrame_Show' (a nil value)
[string "@AuctionHouseNotifications/Interface.lua"]:9: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5281: in function <FrameXML/ChatFrame.lua:5227>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4938: in function <FrameXML/ChatFrame.lua:4937>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4974: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:141_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:141_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_Show' (a nil value)"

**Comment by BrenoLudgero** [comment]
The method used to open the addon's options interface was deprecated in version 10.0.0 ([WoW Interface forum post](https://www.wowinterface.com/forums/showthread.php?t=59211)).

An updated custom version was sent to you via private message in WoW Interface.

**Comment by 40P3** [comment]
Updated the install with the latest file, still getting an error, bit different now:

15x ...rfaceAuctionHouseNotifications/Interface.lua:9: attempt to call global 'InterfaceOptionsFrame_Show' (a nil value)
[string "@AuctionHouseNotifications/Interface.lua"]:9: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5281: in function <FrameXML/ChatFrame.lua:5227>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4938: in function <FrameXML/ChatFrame.lua:4937>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4974: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:141_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:141_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_Show' (a nil value)"

**Comment by BrenoLudgero** [comment]
The error still points to calling the function 'InterfaceOptionsFrame_Show' from the file 'Interface.lua', but neither should be present now. Could you please double check if all the files in the addon folder have been replaced with the latest files, @40P3?

**Comment by BrenoLudgero** [comment]
The changes were tested and the latest version (1.3.0) is now compatible with Retail / Mainline.
